"""Fixing fk

Revision ID: 222199ef058e
Revises: 8a1c3cce5c5c
Create Date: 2022-05-26 22:20:50.408326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222199ef058e'
down_revision = '8a1c3cce5c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
