"""init

Revision ID: 8a1c3cce5c5c
Revises: 
Create Date: 2022-05-26 14:08:09.880610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a1c3cce5c5c'
down_revision = None
branch_labels = None
depends_on = None

GenderType = sa.Enum('FEMALE', 'MALE', 'NOT_MENTIONED', name='GenderType')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('import_id')
    )
    op.create_table('citizen',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('apartment', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', GenderType, nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['import.import_id'], ),
    sa.PrimaryKeyConstraint('import_id', 'citizen_id')
    )
    op.create_index(op.f('ix_citizen_town'), 'citizen', ['town'], unique=False)
    op.create_table('relation',
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('relative_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_id', 'citizen_id'], ['citizen.import_id', 'citizen.citizen_id'], ),
    sa.ForeignKeyConstraint(['import_id', 'relative_id'], ['citizen.import_id', 'citizen.citizen_id'], ),
    sa.PrimaryKeyConstraint('import_id', 'citizen_id', 'relative_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation')
    op.drop_table('citizen')
    op.drop_table('import')
    GenderType.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
